Repository Soumyajit2825/MESSI_MANIA, pull requests merged in 2022-10, with the labels that each got.

#9 Upgraded page view
  Image/stats-background.jpg
  home.html
  style.css
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#11 Hamburger
  app.js
  home.html
  style.css
Labels: hactoberfest, hacktoberfest-accepted

#15 Resolved the Gap Issue in Webpage
  home.html
  style.css
Labels: hactoberfest, hacktoberfest-accepted

#21 Responsiveness of stats-main table section fixed
  style.css
Labels: hactoberfest, hacktoberfest-accepted

#25 Toggle menu
  Image/stars.webp
  app.js
  home.html
  style.css
Labels: enhancement, help wanted, good first issue, hactoberfest, hacktoberfest-accepted

#27 Added a Scroll Button
  Image/favicon/top-scroll-icon.png
  index.html
  style.css
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#28 added bg color and font
  style.css
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#29 Minor Text edit and Removed Unused Span.
  index.html
Labels: hacktoberfest-accepted

#34 This PR fixes both #30 and #31
  app.js
  index.html
  style.css
Labels: bug, enhancement, help wanted, good first issue, hactoberfest, hacktoberfest-accepted

#39 added contributers list and website preview
  README.md
Labels: bug, documentation, enhancement, help wanted, good first issue, hactoberfest, hacktoberfest-accepted

#40 Navbar Upgradation
  index.html
  style.css
Labels: enhancement, good first issue, hactoberfest, hacktoberfest-accepted

#43 added icons for social links and updated styles for links
  index.html
  style.css
Labels: hactoberfest, hacktoberfest-accepted

#46 Font Family Updated and General Changes
  Image/mini__R5I4403.jpeg
  Image/mini__R5I4403.jpg
  index.html
  style.css
Labels: hactoberfest, hacktoberfest-accepted

#51 Added a Video hover play feature
  index.html
Labels: enhancement, hactoberfest, hacktoberfest-accepted

#54 Removing Sign up/Login link
  README.md
  index.html
Labels: hactoberfest, hacktoberfest-accepted

#55 overflow fixed
  style.css
Labels: bug, hactoberfest, hacktoberfest-accepted

#57 stats table responsiveness fixed
  index.html
  style.css
Labels: bug, hactoberfest, hacktoberfest-accepted

#60 Update index.html
  index.html
Labels: documentation, hacktoberfest-accepted

#62 facts section created
  index.html
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#66 Navbar styling.Issue#52
  Image/backgroundNav.jpg
  index.html
  style.css
Labels: hactoberfest, hacktoberfest-accepted
