Repository Soumyajit2825/MESSI_MANIA, pull requests merged in 2024-01, with the labels that each got.

#78 Add more stat in STATS section
  Image/Argentina_national_football_team_logo.svg.png
  index.html
Labels: enhancement, easy, apertre

#79 Fixed the Dark / Light mode issue , issue #70
  style.css
Labels: easy, apertre

#88 Sayan
  app.js
  index.html
  style.css
Labels: apertre, hard

#95 Make the footer responsive and beautiful
  index.html
  style.css
Labels: apertre, medium

#96 Animated card
  Image/_132055952_gettyimages-1451356967.webp
  Image/sddefault.jpg
  index.html
  style.css
Labels: easy, apertre

#102 css changes made
  index.html
  style.css
Labels: easy, apertre

#101 fixed photo section hover issue
  style.css
Labels: easy, apertre

#109 Animated card
  Image/c1_1.png
  Image/c1_2.png
  Image/c2_1.png
  Image/c2_2.png
  Image/im1.png
  Image/im2.png
  app.js
  index.html
  style.css
  test.html
Labels: enhancement, apertre, medium

#112 Added image popup effect
  Image/0_GettyImages-1313922671jpgong.jpg
  Image/6WHENYGXDJIB7KC72MMN3ZIQWU.jpg
  Image/Leo.jpg
  Image/Lionel-Messi-Barcelona-Champions-League-final.jpg
  Image/c1_1.png
  Image/c1_2.png
  Image/c2_1.png
  Image/c2_2.png
  Image/gettyimages-846141966-612x612.jpg
  Image/im1.png
  Image/im2.png
  Image/leo-raise.jpg
  Image/lionel-messi-fc-barcelona-uefa-champions-league-quarter-final-second-leg-match-juventus-194645949.jpg
  Image/lionel-messi-hd-wallpaperkwhcv.jpg
  Image/lionel-messi-soccer-photoshop-effects-wallpaper-preview.jpg
  Image/messi-ronaldo-1593920966.jpg
  Image/messi-une.jpg
  Image/stats-background.jpg
  app.js
  index.html
  style.css
Labels: enhancement, apertre, medium

#116 Enhanced the scrollbar
  style.css
Labels: enhancement, easy, apertre

#115 Make the carousel automatic
  app.js
  index.html
  style.css
Labels: enhancement, easy, apertre

#120 Update readme.md
  README.md
Labels: documentation, easy, apertre

#124 Improved visibility for hamburger menu
  app.js
  style.css
Labels: easy, apertre

#125 Changed favicon
  Image/favicon/favicon.png
  Image/favicon/favicon2.png
  index.html
Labels: easy, apertre

#126 issue #118 animation on scroll
  aos/aos.css
  aos/aos.js
  index.html
Labels: easy, apertre

#134 Make The Website Responsive
  style.css
Labels: bug, easy, apertre

#136 Top Scroll updated
  Image/scroll.png
  app.js
  index.html
Labels: easy, apertre

#138 hamburger
  style.css
Labels: easy, apertre

#137 ui improvement on where is messi
  Image/leo-raise1.png
  Image/leo-raise2.png
  index.html
  style.css
  test.html
  test2.html
Labels: bug, easy, apertre

#145 Corrected the swapped pics
  index.html
Labels: bug, easy, apertre

#147 Timeline added
  index.html
  timeline.css
  timeline.js
  tyu.png
  uio.png
Labels: apertre, medium

#146 Performance Enhanced and Search Engine Optimised
  Image/0_GettyImages-1313922671jpgong.webp
  Image/220807075403-messi-bicycle-kick-0807-restricted-large-169.webp
  Image/2bee4c5f556d3e4264a0f22cfb5c4004e779d3b1.webp
  Image/4000.webp
  Image/45de7a047b514046a3cbb1bfb00ffe2b.webp
  Image/6WHENYGXDJIB7KC72MMN3ZIQWU.webp
  Image/Argentina_national_football_team_logo.svg.webp
  Image/GettyImages-476288434_(1).webp
  Image/Leo.webp
  Image/Ligue_1_Uber_Eats_logo.svg.webp
  Image/Lionel-Messi-Barcelona-Champions-League-final.webp
  Image/Mundial-sub-20.webp
  Image/Paris_Saint-Germain_F.C...webp
  Image/TELEMMGLPICT000267249163_1_trans_NvBQzQNjv4BqqVzuuqpFlyLIwiB6NTmJwauLYewjGO21NF-o1gxbkUI.webp
  Image/WhatsApp-Image-2023-08-20-at-07.11.23-1024x683.webp
  Image/backgroundNav.webp
  Image/c1_1.webp
  Image/c1_2.webp
  Image/c2_1.webp
  Image/c2_2.webp
  Image/calender.webp
  Image/cropped-messi-logo-01.webp
  Image/download.webp
  Image/gettyimages-846141966-612x612.webp
  Image/goat-messi.webp
  Image/im1.webp
  Image/im2.webp
  Image/jpg_webp.zip
  Image/julienscussel_23-10-30_0304-scaled.webp
  Image/leo-raise.webp
  Image/leo-raise2.webp
  Image/lionel-messi-fc-barcelona-uefa-champions-league-quarter-final-second-leg-match-juventus-194645949.webp
  Image/lionel-messi-hd-wallpaperkwhcv.webp
  Image/lionel-messi-soccer-photoshop-effects-wallpaper-preview.webp
  Image/logo.webp
  Image/messi-goat.webp
  Image/messi-lletres.webp
  Image/messi-ronaldo-1593920966.webp
  Image/messi-small-width.webp
  Image/messi-une.webp
  Image/messi_barca.webp
  Image/messi_v_cr7.webp
  Image/mini__R5I4403.webp
  Image/png_webp.zip
  Image/pngwing.com.webp
  Image/scroll.webp
  Image/sddefault.webp
  Image/sneek.webp
  Image/stats-background.webp
  Image/wp11948236.webp
  app.js
  index.html
  style.css
Labels: easy, apertre

#151 Add Horizontal Scrollbar in Time line
  index.html
Labels: easy, apertre
