Repository Soumyajit2825/MESSI_MANIA, pull requests merged in 2025-03, with the labels that each got.

#167 Home link made working
  index.html
Labels: easy, apertre2.0

#169 Added Arrow button in timeline section
  index.html
  timeline.css
  timeline.js
Labels: easy, apertre2.0

#174 License added
  License.md
Labels: apertre2.0, doc

#176 Fix: Improved stats section
  app.js
  style.css
Labels: easy, apertre2.0

#177 Modified age
  app.js
  index.html
Labels: easy, apertre2.0

#178 added contact us page
  contact.html
  image.png
  index.html
Labels: easy, apertre2.0

#190 Adding Pro Footer
  index.html
  style.css
Labels: medium, apertre2.0

#193 Added a quize section to the Messi fan page
  index.html
  quize.js
Labels: medium, apertre2.0

#194 Footer Updated✅
  index.html
Labels: easy, apertre2.0

#197 [Linked the footer section components with their respective ones]
  index.html
Labels: easy, apertre2.0

#219 Copa america 2015 lost date fixed
  404.html
  index.html
Labels: easy, apertre2.0
